home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    
    path('location/', views.location, name='location'),
    path('cheap_product/', views.cheap_product, name='cheap_product'),
    path('payment/', views.payment, name='payment'),
    
    path('products/', views.products, name='products'),
    path('products/<int:product_id>/', views.product_id, name='product_id'),
    
    path('favorite/', views.favorites, name='favorite'),
    path('favorite/<int:product_id>/', views.toggle_favorite, name='toggle_favorite'),
    
    path('cart/', views.cart, name='cart'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path("cart/remove/<int:product_id>/", views.remove_from_cart, name="remove_from_cart"),
    
    path('sobre/', views.sobre, name='sobre'),
    path('contato/', views.contato, name='contato'),
    
]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary_storage.storage import MediaCloudinaryStorage #type:ignore


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        
    name = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=254)
    description = models.TextField(blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    
    image = models.ImageField(upload_to='products/', storage=MediaCloudinaryStorage())
   
    def __str__(self):
        return self.name
    
    
class Favorite(models.Model):
    session_key  = models.CharField( max_length=50)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('session_key', 'product')
        
    def __str__(self):
        return f'{self.session_key } -> {self.product.name}'

   
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('user', 'product')
        
    def __str__(self):
        return f'{self.user.username} -> {self.product.name}'

home/views/forms.py
import requests
from django import forms
from django.core.exceptions import ValidationError

class EnderecoForm(forms.Form):
    cep = forms.CharField(label="CEP", max_length=9)

    def clean_cep(self):
        cep = self.cleaned_data['cep'].replace('-', '').strip()

        if len(cep) != 8 or not cep.isdigit():
            raise ValidationError("CEP deve conter 8 dígitos numéricos.")

        response = requests.get(f'https://viacep.com.br/ws/{cep}/json/')
        if response.status_code != 200:
            raise ValidationError("Erro ao consultar o CEP.")

        data = response.json()

        if data.get('erro'):
            raise ValidationError("CEP não encontrado.")

        # Armazena os dados do endereço no form para uso posterior
        self.cleaned_data['logradouro'] = data.get('logradouro')
        self.cleaned_data['bairro'] = data.get('bairro')
        self.cleaned_data['cidade'] = data.get('localidade')
        self.cleaned_data['uf'] = data.get('uf')

        return cep

home/views/home_views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.core.paginator import Paginator
from home.models import Product, Category, Favorite
from .forms import EnderecoForm
from django.db.models import Q



def index(req):
    category_id = req.GET.get('category')
    products = Product.objects.order_by('-id')
    
    #entender este trecho
    user_favorites = set()
    if not req.session.session_key:
        req.session.save()
    
    session_key = req.session.session_key
    
    user_favorites = set(
        Favorite.objects.filter(session_key=session_key)
        .values_list('product_id', flat=True)
    )
    
    if category_id:
        products = products.filter(category_id=category_id)
        
    categories = Category.objects.all()
    
    paginator = Paginator(products, 4)
    page_number = req.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    endereco = req.session.get('endereco', {})
    
    context = {
        'page_obj':page_obj, 
        'site_title': 'Home',
        'selected_category': category_id,
        'categories': categories,
        'user_favorites': user_favorites,
        'endereco':endereco
        ,}
    
    return render( req ,
        'home/index.html',
        context,)
   
def search(req):
    search_value = req.GET.get('q','').strip()
    
    user_favorites = set()
    if not req.session.session_key:
        req.session.save()
    
    session_key = req.session.session_key
    
    user_favorites = set(
        Favorite.objects.filter(session_key=session_key)
        .values_list('product_id', flat=True)
    )
    
    if search_value == '':
        return redirect('home:index')
    
    products = Product.objects.filter(
        Q(name__icontains=search_value) |
        Q(description__icontains=search_value) |
        Q(price__icontains=search_value) |
        Q(category__name__icontains=search_value)
    ).order_by('-id')
    
    paginator = Paginator(products, 10)
    page_number = req.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': f'Search - {search_value}',
        'search_value': search_value,
        'user_favorites': user_favorites,
    }
    
    return render(
        req,
        'home/index.html',
        context,
        
    )

def cart(req):
    cart = req.session.get("cart", {})
    category_id = req.GET.get('category')   
    
    products = Product.objects.all()
     
    if category_id:
        products = products.filter(category_id=category_id)
        
    categories = Category.objects.all()
    total = sum(float(item["price"]) * int(item["quantity"]) for item in cart.values())
    
    context = {
        "cart": cart,
        "total": total,
        "site_title": "Carrinho",
        'selected_category': category_id,
        'categories': categories,
    }
    
    return render(req,"home/cart.html", context)

def clear_cart(req):
    if "cart" in req.session:
        del req.session["cart"]
        req.session.modified = True
    return redirect("home:cart")

def add_to_cart(req,product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = req.session.get("cart", {})
    
    if str(product_id) in cart:
        cart[str(product_id)]["quantity"] += 1
        
    else:
        cart[str(product_id)] = {
            "name": str(product.name),              # string simples
            "price": float(product.price),          # número simples
            "quantity": 1,                          # número simples
            "image": str(product.image.url) if product.image else "",  # string simples
        }
        
    req.session["cart"] = cart
    req.session.modified = True
    return redirect("home:cart")

def remove_from_cart(req,product_id):
    cart = req.session.get("cart", {})
    if str(product_id) in cart:
        cart[str(product_id)]["quantity"] -= 1
        req.session["cart"] = cart
        req.session.modified = True
        
    if  cart[str(product_id)]["quantity"] <= 0:
        del cart[str(product_id)]
        
    return redirect("home:cart")
    
def favorites(req):
    if not req.session.session_key:
        req.session.create()
        
    session_key = req.session.session_key
    
    favorites = Favorite.objects.filter(session_key=session_key).select_related("product")
    products = Product.objects.all()
    
    category_id = req.GET.get('category')    
    if category_id:
        products = products.filter(category_id=category_id)
        
    categories = Category.objects.all()
    
    context = {
        'selected_category': category_id,
        'site_title': 'Favoritos',
        'categories': categories,
        'favorites': favorites,
    }
    return render(req, "home/favorites.html", context)

def toggle_favorite(req,product_id):
    if not req.session.session_key:
        req.session.create()
        
    session_key = req.session.session_key
    product = get_object_or_404(Product, id=product_id)
    
    favorite, created = Favorite.objects.get_or_create(session_key=session_key, product=product)

    if not created:
        # Já era favorito → remove
        favorite.delete()
        
    return redirect('home:products')

def products(req):
    category_id = req.GET.get('category')
    products = Product.objects.order_by('-id')
    
     #entender este trecho
    user_favorites = set()
    if not req.session.session_key:
        req.session.save()
    
    session_key = req.session.session_key
    
    user_favorites = set(
        Favorite.objects.filter(session_key=session_key)
        .values_list('product_id', flat=True)
    )
     
    if category_id:
        products = products.filter(category_id=category_id)
        
    categories = Category.objects.all()

    paginator = Paginator(products, 12)
    page_number = req.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj':page_obj, 
        'selected_category': category_id,
        'categories': categories,
        'site_title': 'Produtos',
        'user_favorites': user_favorites
        ,}
    
    return render( req ,
        'home/products.html',
        context,) 
    
def product_id(req,product_id):
    try:
        single_product = Product.objects.get(pk=product_id)
        categories = Category.objects.all()
        
        if not req.session.session_key:
            req.session.save()
        
        session_key = req.session.session_key
        
        user_favorites = set(
            Favorite.objects.filter(session_key=session_key)
            .values_list('product_id', flat=True)
        )    
        
        context = {
            'categories': categories,
            'product': single_product,
            'site_title':f"{single_product.name} - Detalhes",
            'user_favorites':user_favorites,
        }
    
    except Product.DoesNotExist:
        return redirect('home:products')
    
    return render(
        req,
        'home/product_id.html',
        context,
    )
    
def sobre(req):
    products = Product.objects.all()
    
    category_id = req.GET.get('category')
    if category_id:
        products = products.filter(category_id=category_id)
        
    categories = Category.objects.all()
    return render( req ,
        'home/sobre.html',{'categories': categories,'site_title': 'Sobre',})

def contato(req):
    products = Product.objects.all()
    
    category_id = req.GET.get('category')
    if category_id:
        products = products.filter(category_id=category_id)
        
    categories = Category.objects.all()
    return render( req ,
        'home/contato.html',{'categories': categories,'site_title': 'Contato',})
    
def location(req):
    endereco_session = req.session.get("endereco", {})
    form = EnderecoForm(req.POST or None)
    
    if form.is_valid():
        endereco = {
            'cep': form.cleaned_data['cep'],
            'logradouro': form.cleaned_data.get('logradouro'),
            'bairro': form.cleaned_data.get('bairro'),
            'cidade': form.cleaned_data.get('cidade'),
            'uf': form.cleaned_data.get('uf'),
        }
        
        # ✅ Salva o dicionário na sessão
        req.session['endereco'] = endereco
        req.session.modified = True
    
        endereco_session = endereco
    
    products = Product.objects.all()
    category_id = req.GET.get('category')
    if category_id:
        products = products.filter(category_id=category_id)
        
    categories = Category.objects.all()
    
    context = {
        'site_title': 'Localização',
        'categories': categories,
        'form': form,
        'endereco': endereco_session,
    }
    return render( req ,
        'home/forms/location.html',context)
       
def payment(req):
    products = Product.objects.all()
    
    category_id = req.GET.get('category')
    if category_id:
        products = products.filter(category_id=category_id)
        
    categories = Category.objects.all()
    return render( req ,
        'home/forms/payment.html',{'categories': categories,'site_title': 'Meios de pagamento',})
    
def cheap_product(req):
    category_id = req.GET.get('category')
    products = Product.objects.filter(price__lte=100).order_by('-id')
    
     #entender este trecho
    user_favorites = set()
    if not req.session.session_key:
        req.session.save()
    
    session_key = req.session.session_key
    
    user_favorites = set(
        Favorite.objects.filter(session_key=session_key)
        .values_list('product_id', flat=True)
    )
    if category_id:
        products = products.filter(category_id=category_id)
        
    categories = Category.objects.all()

    paginator = Paginator(products, 10)
    page_number = req.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj':page_obj, 
        'site_title': 'Produtos menos de R$100',

home/templates/home/cart.html
{% extends "global/base.html" %} {% block content %}
<div class="cart-container">
  <h1 class="cart-title">Meu Carrinho</h1>

  {% if cart %}
  <ul class="cart-list">
    {% for product_id, item in cart.items %}
    <li class="cart-item">
      {% if item.image %}
      <img
        src="{{item.image}}"
        alt="{{ item.name }}"
        class="cart-item-image"
      />
      {% endif %}

      <div class="cart-item-info">
        <a href="{% url 'home:product_id' product_id %}" class="cart-item-name"
          >{{ item.name }}</a
        >
        <p class="cart-item-price">R$ {{ item.price|floatformat:2 }}</p>
        <p class="cart-item-quantity">Quantidade: {{ item.quantity }}</p>
      </div>

      <div class="cart-item-actions">
        <a
          href="{% url 'home:remove_from_cart' product_id=product_id %}"
          class="btn-remove"
          >Remover</a
        >
        <a
          href="{% url 'home:add_to_cart' product_id=product_id %}"
          class="btn-add"
          >Adicionar</a
        >
      </div>
    </li>
    {% endfor %}
  </ul>

  <h2 class="cart-total">Total: R$ {{ total|floatformat:2 }}</h2>

  {% else %}
  <p class="cart-empty">O carrinho está vazio.</p>
  {% endif %}
</div>
{% endblock %}

home/templates/home/category.html
<form method="get" class="category-form">
    <label for="category" class="category-label">Categoria:</label>
    <select name="category" id="category" class="category-select">
        {% for cat in categories %}
            <option value="{{ cat.id }}">{{ cat.name }}</option>
        {% endfor %}
    </select>
    <button type="submit" class="btn-category-submit">Filtrar</button>
</form>

home/templates/home/contato.html
{% extends "global/base.html" %} 
{% block content %}
<div class="contact-section">
  <h1>Contato</h1>

 <ul class="contact-list">
  <li><a href="https://github.com/ronesanttos" target="_blank">🐙 GitHub</a></li>
  <li><a href="https://www.linkedin.com/in/rony-santos-9619a1267" target="_blank">💼 LinkedIn</a></li>
  <li><a href="https://www.instagram.com/rony__santos_" target="_blank">📷 Instagram</a></li>
</ul>
</div>
{% endblock content %}

home/templates/home/favorites.html
{% extends "global/base.html" %} {% block content %}
<div class="favorites-container">
  <h1 class="favorites-title">Meus Favoritos</h1>

  {% if favorites %}
  <ul class="favorites-list">
    {% for fav in favorites %}
    <li class="favorite-item">
      {% if fav.product.image %}
      <img src="{{ fav.product.image.url }}" alt="{{ fav.product.name }}" />
      {% endif %}

      <a href="{% url 'home:product_id' fav.product.id %}" class="favorite-name"
        >{{ fav.product.name }}</a
      >
      <span class="favorite-price"
        >R$ {{ fav.product.price|floatformat:2 }}</span
      >
      <a
        href="{% url 'home:toggle_favorite' fav.product.id %}"
        class="btn-favorite-item"
        >❤️</a
      >
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p class="no-favorites">Você não tem produtos favoritos.</p>
  {% endif %}
</div>
{% endblock %}

home/templates/home/index.html
{% extends "global/base.html" %} {% block content %}
<div class="info_cards">
  <ul>
    {% if not endereco %}
    <li>
      <a href="{% url 'home:location' %}">
        <strong>Insira sua localização</strong>
        <p>Confira os custos e prazos de entrega.</p>
        <span>Informar localização</span>
      </a>
    </li>
    {% endif %}

    <li>
      <a href="{% url 'home:payment' %}">
        <strong>Meios de pagamento</strong>
        <p>Pague suas compras com rapidez e segurança.</p>
        <span>Mostrar meios</span>
      </a>
    </li>
    <li>
      <a href="{% url 'home:cheap_product' %}">
        <strong>Menos de R$100</strong>
        <p>Confira produtos com preços baixos.</p>
        <span>Mostrar produtos</span>
      </a>
    </li>
  </ul>
</div>
<div class="products-container">
  {% if page_obj %}
  <div class="products-list">
    {% for product in page_obj %}
    <div class="product-card">
      {% if product.image %}
      <img
        src="{{ product.image.url }}"
        alt="{{ product.name }}"
        class="product-image"
      />
      {% endif %}

      <div class="product-info">
        <a href="{% url 'home:product_id' product.id %}" class="product-name">
          {{ product.name }}
        </a>
        <p class="product-description">{{ product.description }}</p>
        <p class="product-price">R$ {{ product.price|floatformat:2 }}</p>

        <div class="product-actions">
          <a href="{% url 'home:add_to_cart' product.id %}" class="btn-add-cart"
            >🛒 Adicionar</a
          >
          <a
            href="{% url 'home:toggle_favorite' product.id %}"
            class="btn-favorite"
          >
            {% if product.id in user_favorites %} ❤️ {% else %} 🤍 {% endif %}
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  {% else %}
  <div class="no-products">
    <h1>Nenhum produto encontrado</h1>
  </div>
  {% endif %}
</div>
{% endblock %}

home/templates/home/product_id.html
{% extends "global/base.html" %}

{% block content %}
<div class="product-detail-container">

    <!-- Detalhes do produto -->
    <div class="product-detail-card">
        <h1 class="product-detail-name">{{ product.name }}</h1>
        <p class="product-detail-description">{{ product.description }}</p>
        <p class="product-detail-price"><strong>Preço:</strong> R$ {{ product.price|floatformat:2 }}</p>

        {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-detail-image">
        {% endif %}

        <a href="{% url 'home:add_to_cart' product.id %}" class="btn-cart-detail">🛒 Adicionar</a>
        <a href="{% url 'home:toggle_favorite' product.id %}" class="btn-favorite-detail">
            {% if product.id in user_favorites %}
                ❤️
            {% else %}
                🤍
            {% endif %}
        </a>
    </div>
</div>
{% endblock %}

home/templates/home/products.html
{% extends "global/base.html" %} {% block content %}
<div class="products-container">

  {% if page_obj %}
  <div class="products-list">
    {% for product in page_obj %}
    <div class="product-card">
      {% if product.image %}
      <img
        src="{{product.image.url}}"
        alt="{{ product.name }}"
        class="product-image"
      />
      {% endif %}

      <div class="product-info">
        <a href="{% url 'home:product_id' product.id %}" class="product-name">
          {{ product.name }}
        </a>
        <p class="product-description">{{ product.description }}</p>
        <p class="product-price">R$ {{ product.price|floatformat:2 }}</p>

        <div class="product-actions">
          <a href="{% url 'home:add_to_cart' product.id %}" class="btn-add-cart"
            >🛒 Adicionar</a
          >
          <a
            href="{% url 'home:toggle_favorite' product.id %}"
            class="btn-favorite"
          >
            {% if product.id in user_favorites %} ❤️ {% else %} 🤍 {% endif %}
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="no-products">
    <h1>Nenhum produto encontrado</h1>
  </div>
  {% endif %}
</div>
{% endblock %}

home/templates/home/sobre.html
{% extends "global/base.html" %} {% block content %}
<div class="about-section">
  <h1>Sobre o Projeto</h1>

  <p>
    Este site foi desenvolvido com <strong>Django</strong> e
    <strong>SQLite</strong>, com o objetivo de praticar e consolidar
    conhecimentos em desenvolvimento web full-stack.
  </p>

  <p>
    Ele está atualmente <strong>hospedado na plataforma
    <a href="https://render.com/" target="_blank">Render</a></strong>, permitindo fácil acesso e testes em ambiente de
    produção, sem a necessidade de configurar servidores locais.
  </p>

  <p>
    Para o gerenciamento de imagens, está sendo utilizado o serviço da
    <strong><a href="https://console.cloudinary.com/app/" target="_blank" >Cloudinary</a></strong>, garantindo maior performance no carregamento e
    manipulação das mídias.
  </p>
  <p>
    Tanto os dados do <strong>carrinho de compras</strong> quanto dos
    <strong>produtos favoritos</strong> são armazenados via sessions, o que
    permite que as informações sejam mantidas mesmo sem a necessidade de login —
    facilitando a navegação e a experiência do usuário de forma anônima.
  </p>

  <p>
    ⚠️ O projeto ainda está em fase de desenvolvimento e pode apresentar
    pequenos bugs. Por exemplo: ao adicionar um produto aos favoritos, o usuário
    é redirecionado para a página inicial — comportamento que será ajustado
    futuramente.
  </p>

  <p>
    A interface utiliza um <strong>CSS básico</strong>, pois o foco principal do projeto é a
    estrutura lógica e o funcionamento da aplicação. Ainda assim, sugestões de
    melhorias visuais são muito bem-vindas!
  </p>
  <p>
    Se você tiver interesse em colaborar com ajustes de estilo ou corrigir
    alguns problemas, o repositório está disponível no GitHub:
    <a href="https://github.com/ronesanttos/virtual_store" target="_blank"
      >github.com/ronesanttos/virtual_store</a
    >
  </p>
</div>

{% endblock content %}